experiment_name: "sample_small"
seed: 123
population_size: 10
generations: 5
mutation:
  per_locus_rate: 0.05

genome:
  loci:
    - name: cooperation
      type: float
      min: 0.0
      max: 1.0
    - name: energy
      type: int
      min: 0
      max: 100
    - name: color
      type: enum
      enum: ["red", "green", "blue"]

scenarios:
  - name: "baseline"
    policy: "rational"
  - name: "spiritual_communal"
    policy: "spiritual"

checkpoint_interval: 1
logging_level: "INFO"
