experiment_name: "multiverse_smoke"
seed: 123456
population_size: 200
generations: 200
max_offspring_per_pair: 3
pairing_policy: "assortative"   # random|assortative|community
mutation:
  per_locus_rate: 0.01
  structural_rate: 0.0001
genome:
  length: 64
  loci:
    - name: cooperation
      type: float
      min: 0.0
      max: 1.0
    - name: curiosity
      type: float
      min: 0.0
      max: 1.0
    - name: rhythm
      type: float
      min: 0.0
      max: 1.0
    - name: metallurgy_bias
      type: float
      min: 0.0
      max: 1.0
scenarios:
  - name: "baseline"
    enable_language: false
    math_injection: false
    money_system: false
    policy: "rational"
  - name: "language_only"
    enable_language: true
    math_injection: false
    money_system: false
    policy: "rational"
  - name: "math_language"
    enable_language: true
    math_injection: true
    money_system: false
    policy: "rational"
  - name: "spiritual_communal"
    enable_language: true
    math_injection: false
    money_system: true
    policy: "spiritual"
checkpoint_interval: 20
logging_level: "INFO"
